@startuml

|客户|
start
:下单;

|商务顾问|
:预约到店时间;
:预约交车时间;
:确认客户已到店;
:订单调整;

fork
:拆分车辆订金;
fork again
:设置保险提供;
end fork

|客户|
:维护指标人;

|收银|
:确认收订金;
while (moby锁车?) is (失败)
|计划员|
:sap建车;
endwhile (成功)
|客户|
:签署合同;
 
|商务顾问|
while (结束考虑期) is (sap锁车失败)

|计划员|
:请到SAP创建车辆;
:到主机厂下单，并录入SAP;
:在SAP设置车辆物流状态;

endwhile (成功)

|商务顾问|
if (是否有金融) then (有)
|金融经理|
:预约面签;
:设置金融方案;
:上传批贷函;
:确认输结果;
|商务顾问|
:客户金融分期已办理成功，已获得批贷函;
:预约客户到店办理首付款交付;
:确定车辆合格证或关单、检验单已上传;
|收银|
:客户已具备支付首付条件，请尽快确认;
else (无)
|收银|
:客户已预约到店支付尾款，请注意确认;
:客户已支付尾款，请尽快确认;
endif

|商务顾问|
:请到sap进行结算操作;
if (是否重签合同) then (是)
|客户|
:重签合同;
endif

|收银|
:订单已具备开票条件，请开票后及时上传;

|精品顾问|
:确认精品施工完成;

|承保顾问|
:办保险;

|验车专员|
:上传输完毕后单据;
:完成代缴购置税及代办临牌;
:完成代办验车上牌;

|交车顾问|
:交车确认单确认;


stop

@enduml