[package]
name = "megatron"
version = "0.1.0"
authors = ["屈文斌 <quwenbin@blchina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
