@startuml
title 手动预约商务顾问

actor "客户" as Customer
participant "应用层" as AppLayer #orange
participant "中台端" as Center
participant "工单中心" as WorkOrder
participant "工作流" as WorkFLow

activate Customer

Customer -> AppLayer: 1、预约商务
activate AppLayer

AppLayer -> Center: 2、获取基础数据
activate Center

Center --> AppLayer: 3、返回
deactivate

AppLayer -> WorkOrder: 4、创建主工单信息
activate WorkOrder

WorkOrder --> AppLayer: 5、返回
deactivate WorkOrder

AppLayer -> WorkFLow: 6、开启工作流
activate WorkFLow

WorkFLow --> AppLayer: 7、返回
deactivate WorkFLow

AppLayer --> Customer: 8、预约成功
deactivate AppLayer
deactivate Customer

@enduml