@startuml

title 自动预约商务顾问

actor "用户" as Customer
participant "应用层" as AppLayer #orange
participant "RocketMQ" as Rocket
participant "中台端" as Center
participant "工单中心" as WorkOrder
participant "工作流" as WorkFLow

activate Customer

Customer -> AppLayer: 1、下单
activate AppLayer

AppLayer ->Rocket: 2、发送自动预约消息
activate Rocket

Rocket --> AppLayer: 3、发送成功
deactivate Rocket

AppLayer --> Customer: 4、下单成功
deactivate Customer
deactivate AppLayer

AppLayer -> Rocket: 6、订阅消息
activate AppLayer
activate Rocket

Rocket --> AppLayer: 7、返回消息
deactivate Rocket

AppLayer -> Center: 8、获取基础数据
activate Center

Center --> AppLayer: 9、返回
deactivate

AppLayer -> WorkOrder: 10、创建主工单信息
activate WorkOrder

WorkOrder --> AppLayer: 11、返回
deactivate WorkOrder

AppLayer -> WorkFLow: 12、开启工作流
activate WorkFLow

WorkFLow --> AppLayer: 13、返回
deactivate WorkFLow

@enduml