@startuml

left to right direction

title **数据库ER图**

object "模板表" as temp
temp : id 主键
temp : name 名称
temp : sort 顺序
temp : template 模板
temp : create_time 创建时间
temp : create_by 创建人
temp : update_time 更新时间
temp : update_by 更新人
temp : dr 逻辑删除标识

object "模板组表" as temp_g
temp_g : id 主键

object "模板与组关系表" as temp_g_r
temp_g_r : id 主键

object "任务组表" as task_g
task_g : id 主键

object "任务表" as task
task : id 主键

temp --> "*" temp_g_r
temp_g --> "*" temp_g_r

temp_g "1" --> "1" task_g

temp_g_r "1" --> "*" task

@enduml