@startuml

title 协同类图

'skinparam packageStyle rect
skinparam backgroundColor #EEEBDC
skinparam roundcorner 20
skinparam sequenceArrowThickness 2
'skinparam handwritten true

class TaskServer<<对外暴露任务服务的能力>> {
    +TemplateGroupDto taskGroupList(String taskGroupId,String myTpye)
    +List<TemplateGroupDto> groupList(String role, String status) throws Exception
    +<T extends TemplateBase>  void taskHandler(TaskContext<T> context)
}

class AlgorithmPoolHandler<<反射具体任务Handler>> {
    +void invoke(TaskContext context) throws Exception
}

AlgorithmPoolHandler *--TaskServer

package com.deepexi.application.workflow.template #green {
    interface TemplateParser {
        +List<UserTask> parseTempl(TaskContext taskContext) throws Exception
    }

    interface TemplateGroupParser {
        +TaskGroup parseTempl(TaskContext taskContext) throws Exception;
    }

    class impl.BoutiqueGroupParser {

    }

    TemplateGroupParser <|-- impl.BoutiqueGroupParser
}

package com.deepexi.application.workflow.task #orange {
    interface TaskHandler {
        +void handler(TaskContext context) throws Exception
    }
    note bottom of TaskHandler
    任务处理接口，所有任务的处理
    都继承此接口
    end note

    class SubscribeCustomerToShopHandler<<客户预约到店>> {
        +void handler(TaskContext context) throws Exception
    }

    TaskHandler <|-- SubscribeCustomerToShopHandler

}

package com.deepexi.application.workflow.taskflow {
    interface FlowTask {
        +void next()
    }
}

@enduml